// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhsbWuZAhuk2gvXhrSVOUfth6W2RekTgI',
    appId: '1:88922437608:web:cdfedec67efe674d1f165d',
    messagingSenderId: '88922437608',
    projectId: 'foodhub-34c19',
    authDomain: 'foodhub-34c19.firebaseapp.com',
    storageBucket: 'foodhub-34c19.appspot.com',
    measurementId: 'G-X5ZJPM2RWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHTYCM6ji9seKdQjH4SjOjSQXysBSkLJs',
    appId: '1:88922437608:android:8e87e5df72b32ee01f165d',
    messagingSenderId: '88922437608',
    projectId: 'foodhub-34c19',
    storageBucket: 'foodhub-34c19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzNKWhvuyDW5YoXSBkxiElqyUXw2uPJog',
    appId: '1:88922437608:ios:eb649a556e5b2b281f165d',
    messagingSenderId: '88922437608',
    projectId: 'foodhub-34c19',
    storageBucket: 'foodhub-34c19.appspot.com',
    iosClientId: '88922437608-rsvstq0cbguh7akaj1fmno234bl3s807.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzNKWhvuyDW5YoXSBkxiElqyUXw2uPJog',
    appId: '1:88922437608:ios:eb649a556e5b2b281f165d',
    messagingSenderId: '88922437608',
    projectId: 'foodhub-34c19',
    storageBucket: 'foodhub-34c19.appspot.com',
    iosClientId: '88922437608-rsvstq0cbguh7akaj1fmno234bl3s807.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodHub',
  );
}
